function plotCostos(yvector1)
%CREATEFIGURE(yvector1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 12-May-2019 02:15:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1);

% Create ylabel
ylabel({'Costos'},'FontWeight','bold');

% Create xlabel
xlabel({'Métodos'},'FontWeight','bold');

% Create title
title({'Costo de métodos para matrix 289x289'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[1 2 3 4 5 6 7],'XTickLabel',...
    {'Cholesky','Doolittle','Givens','Gauss Jacobbi','Gauss Seidel','Householder','QR'});
