function plotErrorSeidelJacobi(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 12-May-2019 00:50:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.775 0.778888888888889]);
hold(axes1,'on');

% Create plot
plot(Y1,'DisplayName','Gauss-Seidel');

% Create plot
plot(Y2,'DisplayName','Gauss-Jacobbi');

% Create ylabel
ylabel('Error','FontWeight','bold');

% Create xlabel
xlabel('Iteraciones','FontWeight','bold');

% Create title
title('Error vs iteraciones matrix 289x289');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 102]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 205000000]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.807248262634708 0.790187755729924 0.0858072929208479 0.0704089520890037]);

