function plotSolutions(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 11-May-2019 16:09:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = bar(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Cholesky');
set(plot1(2),'DisplayName','Doolittle');
%set(plot1(3),'DisplayName','Givens');
set(plot1(3),'DisplayName','Gauss-Jacobbi');
set(plot1(4),'DisplayName','Gauss-Seidel');
set(plot1(5),'DisplayName','Householder');
set(plot1(6),'DisplayName','QR');

% Create ylabel
ylabel({'Valores'},'FontWeight','bold');

% Create xlabel
xlabel({'Variables vector X'},'FontWeight','bold');

% Create title
title({'Valores de vector X con matrix de 289x289'});

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.791409374688744 0.649848733430765 0.0858072929208477 0.23388365304695]);

