function plotTiempos(yvector1)
%CREATEFIGURE(yvector1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 12-May-2019 03:04:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1);

% Create ylabel
ylabel({'Tiempo [s]'},'FontWeight','bold');

% Create xlabel
xlabel({'Métodos'},'FontWeight','bold');

% Create title
title({'Tiempo ejecución de métodos para matrix 289x289'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',[1 2 3 4 5],'XTickLabel',...
    {'Cholesky','Givens','Gauss Seidel','QR','Mínimos cuadrados'});
